In [1]:
##Test from customize image
## importing classes from the file that is located in the different folder
from tensorflow.keras import backend as k
from keras.preprocessing.image import ImageDataGenerator
from keras.preprocessing.image import img_to_array
from keras.preprocessing.image import save_img
from sklearn.model_selection import train_test_split
from keras.optimizers import SGD
from keras.optimizers import Adam
from keras.models import load_model
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import classification_report
from sklearn.utils.multiclass import unique_labels
import imutils 
from imutils import paths
from keras.optimizers import Adam
import pickle
import matplotlib.pyplot as plt
import cv2
import random
import numpy as np
import pandas as pd
import sys
import os

Using TensorFlow backend.


In [2]:
#reading imagepaths csv files and arranging datas according to the imagepath from folders
datapaths = ['../Dataset/AdienceDataset/original/csv/fold_4_data.csv']#,'../Dataset/AdienceDataset/csv/fold_1_data.csv','../Dataset/AdienceDataset/csv/fold_2_data.csv','../Dataset/AdienceDataset/csv/fold_3_data.csv','../Dataset/AdienceDataset/csv/fold_4_data.csv']
image_size=(48,48)
folder= []
filename = []
faceid = []
age = []
gender = []
for datapath in datapaths:
    #print (datapath)
    data = pd.read_csv(datapath)
    folder +=  data['user_id'].tolist()
    filename += data['original_image'].tolist()
    faceid += data['face_id'].tolist()
    age += data['age'].tolist()
    gender += data['gender'].tolist()  
folder = np.array(folder)
filename = np.array(filename)
faceid  = np.array(faceid).astype(int)
age = np.array(age)
gender = np.array(gender)
    

In [5]:
import pickle

DATA_PATH = "../pickle/csv_pickle"
infile = open(DATA_PATH+'/X_ocsv4_75.pickle','rb')
datavalue = pickle.load(infile)
 


[[[ 0.20784314  0.19215686  0.12941176]
  [ 0.20784314  0.19215686  0.12941176]
  [ 0.19215686  0.17647059  0.11372549]
  ...
  [ 0.36470588  0.34901961  0.28627451]
  [ 0.16862745  0.17647059  0.10588235]
  [ 0.10588235  0.11372549  0.04313725]]

 [[ 0.21568627  0.20784314  0.12941176]
  [ 0.22352941  0.2         0.1372549 ]
  [ 0.23921569  0.22352941  0.16078431]
  ...
  [ 0.34117647  0.34901961  0.27843137]
  [ 0.30196078  0.30980392  0.23921569]
  [ 0.22352941  0.23137255  0.16078431]]

 [[ 0.2         0.17647059  0.1372549 ]
  [ 0.2         0.17647059  0.11372549]
  [ 0.19215686  0.17647059  0.11372549]
  ...
  [ 0.34901961  0.35686275  0.28627451]
  [ 0.37254902  0.38039216  0.30980392]
  [ 0.14509804  0.14509804  0.10588235]]

 ...

 [[-0.21568627 -0.27058824 -0.2627451 ]
  [-0.21568627 -0.28627451 -0.2627451 ]
  [-0.17647059 -0.23137255 -0.20784314]
  ...
  [ 0.19215686  0.16862745  0.23921569]
  [ 0.21568627  0.19215686  0.2627451 ]
  [ 0.10588235  0.08235294  0.15294118]]

 [

In [4]:
# grab the image paths and randomly shuffle them
print("[INFO] loading images...")
base_dir = '../Dataset/age_gender'
os.mkdir(base_dir)

[INFO] loading images...


In [17]:
#Running Sucessfully

#train_dir = os.path.join(base_dir, 'train')
#validation_dir = os.path.join(base_dir, 'validation')
imPath = []
inPath = "../Dataset/AdienceDataset/aligned/"
fileex="landmark_aligned_face"
c = 0
for i in range (folder.shape[0]):
    folder1 = str(age[i])
    folder2 = str(gender[i])
    age_dir = os.path.join(base_dir, folder1)
    gender_dir = os.path.join(age_dir, folder2)
    if os.path.isdir(age_dir)== False:
         os.mkdir(age_dir)
      
    if os.path.isdir(gender_dir)== False:
         os.mkdir(gender_dir)
    image = datavalue[i]
    if str(age[i])== "(25, 32)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(25, 32)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(25, 32)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(25, 32)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    if str(age[i])== "(27, 32)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(27, 32)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(27, 32)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(27, 32)_"+str(gender[i])+"_"+str(c)+'.jpg', image)        
    if str(age[i])== "(38, 42)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(38, 42)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(38, 42)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(38, 42)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "(0, 2)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(0, 2)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(0, 2)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(0, 2)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "(15, 20)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(15, 20)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(15, 20)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(15, 20)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "(38, 43)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(38, 43)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(38, 43)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(38, 43)_"+str(gender[i])+"_"+str(c)+'.jpg', image)        
    elif str(age[i])== "(38, 48)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(38, 48)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(38, 48)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(38, 48)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "(4, 6)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(4, 6)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(4, 6)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(4, 6)_"+str(gender[i])+"_"+str(c)+'.jpg', image) 
    elif str(age[i])== "(48, 53)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(48, 53)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(48, 53)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(48, 53)_"+str(gender[i])+"_"+str(c)+'.jpg', image)        
    elif str(age[i])== "(8, 12)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(8, 12)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(8, 12)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(8, 12)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "(8, 23)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(8, 23)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(8, 23)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(8, 23)_"+str(gender[i])+"_"+str(c)+'.jpg', image)        
    elif str(age[i])== "(60, 100)":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"(60, 100)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"(60, 100)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"(60, 100)_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "3":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"3_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"3_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"3_"+str(gender[i])+"_"+str(c)+'.jpg', image)        
    elif str(age[i])== "13":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"13_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"13_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"13_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(age[i])== "22":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"22_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"22_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"22_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(age[i])== "23":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"23_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"23_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"23_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "2":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"2_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"2_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"2_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "29":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"29_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"29_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"29_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "32":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"32_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"32_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"32_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "56":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"56_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"56_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"56_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "57":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"57_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"57_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"57_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "34":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"34_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"34_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"34_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "42":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"42_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"42_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"42_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "46":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"46_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"46_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"46_"+str(gender[i])+"_"+str(c)+'.jpg', image)
    elif str(age[i])== "35":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"35_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"35_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"35_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(age[i])== "36":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"36_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"36_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"36_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(age[i])== "45":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"45_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"45_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"45_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(age[i])== "55":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"55_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"55_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"55_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(age[i])== "58":
        if str(gender[i])=="f":
            c=c+1
            save_img(gender_dir+"/"+"58_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        elif str(gender[i])=="m":
            c=c+1
            save_img(gender_dir+"/"+"58_"+str(gender[i])+"_"+str(c)+'.jpg', image)
        else:
            c=c+1
            save_img(gender_dir+"/"+"58_"+str(gender[i])+"_"+str(c)+'.jpg', image)     
    elif str(gender[i])==" " or str(age[i])==" " or str(age[i])=="None":
        continue
    
